{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  github-client-id: {{ .Values.secrets.githubClientID | quote }}
  github-client-secret: {{ .Values.secrets.githubClientSecret | quote }}
  github-webhook-secret: {{ .Values.secrets.githubWebhookSecret | quote }}
  github-app-id: {{ .Values.secrets.githubAppID | quote }}
  github-private-key: {{ .Values.secrets.githubPrivateKey | quote }}
  github-installation-id: {{ .Values.secrets.githubInstallationID | quote }}
  slack-bot-token: {{ .Values.secrets.slackBotToken | quote }}
  slack-signing-secret: {{ .Values.secrets.slackSigningSecret | quote }}
{{- end }}
